module.exports = {
    darkMode: 'class',
    content: [
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    safelist: [
        'button-primary',
        'button-secondary',
        'button-danger',
        'button-outline',
        'button-ghost',
        'button-lg',
        'button-md',
        'button-sm',
        'button-base',
        'gap-1',
        'gap-2',
        'gap-4',
        'gap-6',
        'gap-8',
        'gap-10',
        'gap-12',
        'gap-14',
        'gap-16',
        'z-0',
        'z-10',
        'z-20',
        'z-30',
        'z-40',
        'z-50',
        'z-60',
        'z-70',
        'z-80',
        'z-90',
        'z-100',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
};
